spring:
  main:
    allow-bean-definition-overriding: true

quickfixj:
  server:
    jmx-enabled: true
    log-factory: slf4j
    message-store-factory: noop
    configString: |
      [default]
      BeginString=FIXT.1.1
      DefaultApplVerID=FIX.5.0SP2
      UseDataDictionary=Y
      TransportDataDictionary=FIXT11.xml
      AppDataDictionary.FIX.5.0SP2=FIX50SP2.modified.xml
      ResetOnLogon=Y
      ResetOnLogout=Y
      ResetOnDisconnect=Y
      ValidateUnorderedGroupFields=N
      ValidateUserDefinedFields=N
      CheckLatency=N
      HeartBtInt=30
      PersistMessages=N
      
      ConnectionType=acceptor
      
      
      [session]
      BeginString=FIXT.1.1
      DefaultApplVerID=FIX.5.0
      SocketAcceptPort=9881
      SenderCompID=EXEC
      TargetCompID=BANZAI
      ConnectionType=acceptor
      TimeZone=Europe/London
      StartTime=17:55:00
      EndTime=17:50:00
server:
  port: 8080

logging:
  group:
    fix: quickfix.ThreadedSocketInitiator, quickfixj.msg.incoming, quickfixj.msg.outgoing
    nadex: com.nadex
    allune: com.allune
  level:
    fix: INFO
    nadex: DEBUG
    allune: INFO

management:
  endpoint:
    quickfixjserver:
      enabled: true
  endpoints:
    web:
      exposure:
        include: quickfixjserver

